resources:
  - ../../base
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: devflow-controller
    namespace: app
    files:
      - config.yaml
    behavior: create
patchesStrategicMerge:
  - deployment-patch.yaml
