apiVersion: apps/v1
kind: Deployment
metadata:
  name: devflow-confole
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devflow-confole
  template:
    metadata:
      labels:
        app: devflow-confole
    spec:
      containers:
        - name: devflow-confole
          env:
            - name: env
              value: dev
