apiVersion: apps/v1
kind: Deployment
metadata:
  name: devflow
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devflow
  template:
    metadata:
      labels:
        app: devflow
    spec:
      containers:
        - name: devflow
          env:
            - name: env
              value: prod
