apiVersion: apps/v1
kind: Deployment
metadata:
  name: devflow-controller
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devflow-controller
  template:
    metadata:
      labels:
        app: devflow-controller
    spec:
      containers:
        - name: devflow-controller
          env:
            - name: env
              value: prod
