apiVersion: apps/v1
kind: Deployment
metadata:
  name: document
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document
  template:
    metadata:
      labels:
        app: document
    spec:
      containers:
        - name: document
          env:
            - name: env
              value: dev
